define([], function() {

    return {
        PROJECT_REFRESH_LIST: "PROJECT_REFRESH_LIST",
        PROJECT_SAVE: "PROJECT_SAVE",
        PROJECT_EDIT: "PROJECT_EDIT",
        PROJECT_EDIT_CANCEL: "PROJECT_EDIT_CANCEL",
        PROJECT_INSERT: "PROJECT_INSERT",
        PROJECT_CREATE: "PROJECT_CREATE",
        PROJECT_DESTROY: "PROJECT_DESTROY",
        TIME_NEXT_PERIOD: "TIME_NEXT_PERIOD",
        TIME_PREV_PERIOD: "TIME_PREV_PERIOD",

        AUTH_FAILED: "AUTH_FAILED",

        SET_CALENDAR: "SET_CALENDAR",
        RESET_CALENDAR: "RESET_CALENDAR",
		
		UNDO : "UNDO"
    }

});