define([], function() {

    return {
        PROJECT_REFRESH_LIST: "PROJECT_REFRESH_LIST",
        PROJECT_SAVE: "PROJECT_SAVE",
        PROJECT_EDIT: "PROJECT_EDIT",
        PROJECT_EDIT_CANCEL: "PROJECT_EDIT_CANCEL",
        PROJECT_INSERT: "PROJECT_INSERT",
        PROJECT_CREATE: "PROJECT_CREATE",
        PROJECT_DESTROY: "PROJECT_DESTROY",
        TIME_NEXT_PERIOD: "TIME_NEXT_PERIOD",
        TIME_PREV_PERIOD: "TIME_PREV_PERIOD",
        TIME_DAYS: "TIME_DAYS",
        TIME_WEEKS: "TIME_WEEKS",
        TIME_MONTHS: "TIME_MONTHS",
        
        AUTH_FAILED: "AUTH_FAILED",

        SET_CALENDAR: "SET_CALENDAR",
        RESET_CALENDAR: "RESET_CALENDAR",
		
		UNDO : "UNDO",
        CONFIRM_OK: "CONFIRM_OK",
        CONFIRM_CANCEL: "CONFIRM_CANCEL",

        SESSION_LOADED: "SESSION_LOADED",

        ADD_ATTENDEE : "ADD_ATTENDEE",
        REMOVE_ATTENDEE: "REMOVE_ATTENDEE",
        PROFILE_LOADED: "PROFILE_LOADED",
        AUTHENTICATION_COMPLETED: "AUTHENTICATION_COMPLETED",
        LOGOUT: "LOGOUT"
    }

});